macro_category_mapping = {
    'adult standards': 'pop',
    'aesthetic rap': 'hip hop',
    'afro soul': 'soul',
    'afrobeats': 'world',
    'afrofuturism': 'electronic',
    'afropop': 'world',
    'alabama rap': 'hip hop',
    'album rock': 'rock',
    'alt z': 'rock',
    'alternative country': 'country',
    'alternative emo': 'emo',
    'alternative hip hop': 'hip hop',
    'alternative metal': 'metal',
    'alternative pop rock': 'pop',
    'alternative r&b': 'r&b',
    'alternative rock': 'rock',
    'amapiano': 'electronic',
    'ambient lo-fi': 'ambient',
    'anime lo-fi': 'ambient',
    'anime rap': 'hip hop',
    'anthem worship': 'worship',
    'arab trap': 'hip hop',
    'argentine hip hop': 'hip hop',
    'art pop': 'pop',
    'art rock': 'rock',
    'asbury park indie': 'indie',
    'atl hip hop': 'hip hop',
    'atl trap': 'hip hop',
    'australian dance': 'electronic',
    'australian hip hop': 'hip hop',
    'australian house': 'electronic',
    'australian pop': 'pop',
    'australian r&b': 'r&b',
    'australian rock': 'rock',
    'baltimore hip hop': 'hip hop',
    'bardcore': 'folk',
    'baroque pop': 'pop',
    'bass house': 'electronic',
    'bass trap': 'electronic',
    'basshall': 'electronic',
    'bedroom pop': 'pop',
    'bedroom r&b': 'r&b',
    'bedroom soul': 'r&b',
    'belgian dance': 'electronic',
    'belgian edm': 'electronic',
    'belgian pop': 'pop',
    'bergamo indie': 'indie',
    'big room': 'electronic',
    'birmingham grime': 'hip hop',
    'black americana': 'blues',
    'blues rock': 'blues',
    'bossbeat': 'hip hop',
    'boston folk': 'folk',
    'boston hip hop': 'hip hop',
    'boston rock': 'rock',
    'boy pop': 'pop',
    'brega funk': 'funk',
    'british indie rock': 'indie',
    'british invasion': 'rock',
    'british singer-songwriter': 'singer-songwriter',
    'british soul': 'r&b',
    'british soundtrack': 'soundtrack',
    'britpop': 'rock',
    'broadway': 'show tunes',
    'bronx drill': 'hip hop',
    'bronx hip hop': 'hip hop',
    'brooklyn drill': 'hip hop',
    'brostep': 'electronic',
    'bubblegrunge': 'grunge',
    'bubblegum dance': 'electronic',
    'cali rap': 'hip hop',
    'canadian contemporary r&b': 'r&b',
    'canadian electronic': 'electronic',
    'canadian hip hop': 'hip hop',
    'canadian pop': 'pop',
    'canadian pop punk': 'pop',
    'canadian punk': 'punk',
    'canadian rock': 'rock',
    'canadian trap': 'hip hop',
    'candy pop': 'pop',
    'cantautora mexicana': 'pop',
    'canzone napoletana': 'pop',
    'ccm': 'christian music',
    'chamber pop': 'pop',
    'charlotte nc indie': 'indie',
    'chicago indie': 'indie',
    'chicago rap': 'hip hop',
    'chill abstract hip hop': 'hip hop',
    'chill phonk': 'hip hop',
    'chill pop': 'pop',
    'chillstep': 'electronic',
    'christian alternative rock': 'rock',
    'christian hip hop': 'hip hop',
    'christian music': 'worship',
    'christian trap': 'hip hop',
    'classic hardstyle': 'electronic',
    'classic italian pop': 'pop',
    'classic rock': 'rock',
    'cloud rap': 'hip hop',
    'colombian pop': 'pop',
    'comedy rap': 'comedy',
    'comedy rock': 'comedy',
    'comic': 'comedy',
    'complextro': 'electronic',
    'conscious hip hop': 'hip hop',
    'contemporary country': 'country',
    'contemporary r&b': 'r&b',
    'corrido': 'latin',
    'corridos tumbados': 'latin',
    'country': 'country',
    'country pop': 'country',
    'country rap': 'country',
    'country rock': 'country',
    'crunk': 'hip hop',
    'cumbia pop': 'latin',
    'dance pop': 'pop',
    'dance rock': 'rock',
    'dancehall': 'reggae',
    'dancehall queen': 'reggae',
    'danish electronic': 'electronic',
    'danish pop': 'pop',
    'dark r&b': 'r&b',
    'dark synthpop': 'electronic',
    'dark trap': 'hip hop',
    'deep disco house': 'electronic',
    'deep euro house': 'electronic',
    'deep house': 'electronic',
    'deep soundtrack': 'soundtrack',
    'deep underground hip hop': 'hip hop',
    'dembow': 'latin',
    'desi hip hop': 'hip hop',
    'detroit hip hop': 'hip hop',
    'detroit trap': 'hip hop',
    'devon indie': 'indie',
    'dfw rap': 'hip hop',
    'didgeridoo': 'world',
    'dirty south rap': 'hip hop',
    'disco': 'disco',
    'downtempo': 'electronic',
    'dream pop': 'pop',
    'dreamgaze': 'rock',
    'drift phonk': 'hip hop',
    'drill': 'hip hop',
    'drill chileno': 'hip hop',
    'drill espanol': 'hip hop',
    'drill italiana': 'hip hop',
    'dutch edm': 'electronic',
    'dutch experimental electronic': 'electronic',
    'dutch hip hop': 'hip hop',
    'dutch house': 'electronic',
    'dutch tech house': 'electronic',
    'east coast hip hop': 'hip hop',
    'edm': 'electronic',
    'electra': 'electronic',
    'electro': 'electronic',
    'electro house': 'electronic',
    'electronic rock': 'rock',
    'electronic trap': 'electronic',
    'electronica': 'electronic',
    'electropop': 'electronic',
    'emo': 'emo',
    'emo rap': 'emo',
    'emo rap italiano': 'emo',
    'emo trap italiana': 'emo',
    'epicore': 'electronic',
    'escape room': 'soundtrack',
    'estonian pop': 'pop',
    'etherpop': 'electronic',
    'euphoric hardstyle': 'electronic',
    'eurodance': 'electronic',
    'europop': 'pop',
    'faroese indie': 'indie',
    'faroese pop': 'pop',
    'fidget house': 'electronic',
    'filter house': 'electronic',
    'filthstep': 'electronic',
    'float house': 'electronic',
    'florida drill': 'hip hop',
    'florida rap': 'hip hop',
    'folk-pop': 'folk',
    'french hip hop': 'hip hop',
    'french pop': 'pop',
    'funk': 'funk',
    'funk 150 bpm': 'funk',
    'funk carioca': 'funk',
    'funk das antigas': 'funk',
    'funk metal': 'funk',
    'funk mtg': 'funk',
    'funk rj': 'funk',
    'funk rock': 'funk',
    'funk viral': 'funk',
    'g funk': 'funk',
    'gambian hip hop': 'hip hop',
    'gaming edm': 'electronic',
    'gangster rap': 'hip hop',
    'garage rock': 'rock',
    'gauze pop': 'pop',
    'gen z singer-songwriter': 'singer-songwriter',
    'german dance': 'electronic',
    'german indie': 'indie',
    'german indie folk': 'indie',
    'german soundtrack': 'soundtrack',
    'ghanaian pop': 'pop',
    'glitchcore': 'electronic',
    'golden age hip hop': 'hip hop',
    'greek indie': 'indie',
    'grime': 'hip hop',
    'grunge': 'grunge',
    'grungegaze': 'grunge',
    'guadalajara indie': 'indie',
    'gymcore': 'electronic',
    'hard bass': 'electronic',
    'hard motivation': 'electronic',
    'hard rock': 'rock',
    'hardcore hip hop': 'hip hop',
    'hi-nrg': 'electronic',
    'high vibe': 'electronic',
    'hip hop': 'hip hop',
    'hip pop': 'pop',
    'horror synth': 'electronic',
    'house': 'electronic',
    'houston rap': 'hip hop',
    'hyperpop italiano': 'pop',
    'hyphy': 'hip hop',
    'icelandic indie': 'indie',
    'icelandic rock': 'rock',
    'indie folk': 'folk',
    'indie hip hop': 'hip hop',
    'indie jazz': 'jazz',
    'indie liguria': 'indie',
    'indie napoletano': 'indie',
    'indie pop': 'pop',
    'indie pop rap': 'pop',
    'indie poptimism': 'pop',
    'indie quebecois': 'indie',
    'indie r&b': 'r&b',
    'indie rock': 'rock',
    'indie rock italiano': 'rock',
    'indie siciliano': 'indie',
    'indie soul': 'soul',
    'indiecoustica': 'indie',
    'indietronica': 'electronic',
    'industrial': 'industrial',
    'industrial metal': 'metal',
    'industrial rock': 'rock',
    'instrumental djent': 'metal',
    'instrumental grime': 'electronic',
    'instrumental hip hop': 'hip hop',
    'instrumental rock': 'rock',
    'irish pop': 'pop',
    'israeli pop': 'pop',
    'italian adult pop': 'pop',
    'italian alternative': 'alternative',
    'italian electronica': 'electronic',
    'italian hip hop': 'hip hop',
    'italian indie pop': 'indie',
    'italian jazz fusion': 'jazz',
    'italian pop': 'pop',
    'italian punk': 'punk',
    'italian reggae': 'reggae',
    'italian soundtrack': 'soundtrack',
    'italian underground hip hop': 'hip hop',
    'jamaican dancehall': 'reggae',
    'japanese old school hip hop': 'hip hop',
    'japanese vgm': 'video game music',
    'jazz funk': 'jazz',
    'jazz pop': 'jazz',
    'jazz trumpet': 'jazz',
    'jazztronica': 'jazz',
    'k-pop': 'pop',
    'k-pop girl group': 'pop',
    'k-rap': 'hip hop',
    'kansas city hip hop': 'hip hop',
    'kazakh pop': 'pop',
    'la indie': 'indie',
    'la pop': 'pop',
    'latin hip hop': 'hip hop',
    'latin pop': 'pop',
    'latin viral pop': 'pop',
    'lgbtq+ hip hop': 'hip hop',
    'lilith': 'indie',
    'lo-fi beats': 'ambient',
    'lo-fi chill': 'ambient',
    'lo-fi jazzhop': 'ambient',
    'lo-fi rap': 'ambient',
    'london rap': 'hip hop',
    'lounge': 'electronic',
    'madchester': 'indie',
    'maga rap': 'hip hop',
    'melancholia': 'electronic',
    'mellow gold': 'rock',
    'melodic drill': 'hip hop',
    'melodic dubstep': 'electronic',
    'melodic rap': 'hip hop',
    'meme': 'comedy',
    'meme rap': 'comedy',
    'memphis hip hop': 'hip hop',
    'memphis phonk': 'hip hop',
    'metal': 'metal',
    'metalcore': 'metal',
    'metropopolis': 'electronic',
    'mexican hip hop': 'hip hop',
    'mexican pop': 'pop',
    'miami hip hop': 'hip hop',
    'milan indie': 'indie',
    'military rap': 'hip hop',
    'minimal tech house': 'electronic',
    'minimal techno': 'electronic',
    'minnesota hip hop': 'hip hop',
    'mississippi hip hop': 'hip hop',
    'modern alternative pop': 'pop',
    'modern alternative rock': 'rock',
    'modern blues rock': 'blues',
    'modern country pop': 'country',
    'modern indie pop': 'pop',
    'modern jungle': 'electronic',
    'modern rock': 'rock',
    'moombahton': 'electronic',
    'musica chihuahuense': 'latin',
    'musica mexicana': 'latin',
    'nashville singer-songwriter': 'singer-songwriter',
    'necrotrap': 'hip hop',
    'neo mellow': 'pop',
    'neo soul': 'r&b',
    'neon pop punk': 'pop',
    'new jersey indie': 'indie',
    'new jersey rap': 'hip hop',
    'new jersey underground rap': 'hip hop',
    'new orleans rap': 'hip hop',
    'new romantic': 'pop',
    'new wave': 'new wave',
    'new wave pop': 'new wave',
    'new york drill': 'hip hop',
    'nigerian hip hop': 'hip hop',
    'nigerian pop': 'pop',
    'nordic soundtrack': 'soundtrack',
    'norteno': 'latin',
    'north carolina hip hop': 'hip hop',
    'nu disco': 'disco',
    'nu jazz': 'jazz',
    'nu metal': 'metal',
    'nyc rap': 'hip hop',
    'oakland hip hop': 'hip hop',
    'oc rap': 'hip hop',
    'ohio hip hop': 'hip hop',
    'old school hip hop': 'hip hop',
    'old school rap francais': 'hip hop',
    'old school thrash': 'metal',
    'orchestral soundtrack': 'soundtrack',
    'ottawa rap': 'hip hop',
    'oxford indie': 'indie',
    'panamanian pop': 'pop',
    'parody': 'comedy',
    'permanent wave': 'rock',
    'philly rap': 'hip hop',
    'phonk': 'hip hop',
    'phonk brasileiro': 'hip hop',
    'piano rock': 'rock',
    'pinoy trap': 'hip hop',
    'pittsburgh rap': 'hip hop',
    'pixie': 'indie',
    'polish hip hop': 'hip hop',
    'political hip hop': 'hip hop',
    'pop': 'pop',
    'pop dance': 'pop',
    'pop edm': 'pop',
    'pop emo': 'pop',
    'pop punk': 'pop',
    'pop r&b': 'pop',
    'pop rap': 'pop',
    'pop reggaeton': 'pop',
    'pop rock': 'rock',
    'pop soul': 'pop',
    'pop urbaine': 'pop',
    'pop venezolano': 'pop',
    'pop virale italiano': 'pop',
    'post-grunge': 'rock',
    'post-teen pop': 'pop',
    'pov: indie': 'indie',
    'progressive electro house': 'electronic',
    'progressive house': 'electronic',
    'progressive uplifting trance': 'electronic',
    'puerto rican pop': 'pop',
    'punjabi pop': 'pop',
    'punk': 'punk',
    'punk blues': 'punk',
    'queens hip hop': 'hip hop',
    'r&b': 'r&b',
    'r&b en espanol': 'r&b',
    'r&b francais': 'r&b',
    'r&b italiano': 'r&b',
    'raboday': 'world',
    'rage rap': 'hip hop',
    'rap': 'hip hop',
    'rap boricua': 'hip hop',
    'rap canario': 'hip hop',
    'rap conciencia': 'hip hop',
    'rap conscient': 'hip hop',
    'rap dominicano': 'hip hop',
    'rap francais': 'hip hop',
    'rap genovese': 'hip hop',
    'rap italiano old school': 'hip hop',
    'rap latina': 'hip hop',
    'rap marseille': 'hip hop',
    'rap metal': 'metal',
    'rap napoletano': 'hip hop',
    'rap rock': 'rock',
    'rap sardegna': 'hip hop',
    'rap siciliano': 'hip hop',
    'rawstyle': 'electronic',
    'rebel blues': 'blues',
    'reggaeton': 'reggae',
    'reggaeton chileno': 'reggae',
    'reggaeton colombiano': 'reggae',
    'rhode island rap': 'hip hop',
    'riot grrrl': 'punk',
    'rochester mn indie': 'indie',
    'rock': 'rock',
    'rome indie': 'indie',
    'roots rock': 'rock',
    'rune folk': 'folk',
    'russian drill': 'hip hop',
    'russian edm': 'electronic',
    'russian electronic': 'electronic',
    'russian hip hop': 'hip hop',
    'sacramento hip hop': 'hip hop',
    'sad lo-fi': 'ambient',
    'sad rap': 'hip hop',
    'sad sierreno': 'latin',
    'scandinavian r&b': 'r&b',
    'scandipop': 'pop',
    'scorecore': 'soundtrack',
    'scream rap': 'hip hop',
    'seattle hip hop': 'hip hop',
    'sertanejo universitario': 'country',
    'sgija': 'hip hop',
    'sheffield indie': 'indie',
    'shimmer pop': 'pop',
    'shiver pop': 'pop',
    'show tunes': 'soundtrack',
    'shred': 'rock',
    'sierreno': 'latin',
    'singer-songwriter': 'singer-songwriter',
    'singer-songwriter pop': 'singer-songwriter',
    'sky room': 'electronic',
    'slap house': 'electronic',
    'slowed and reverb': 'ambient',
    'social media pop': 'pop',
    'soft rock': 'rock',
    'solo wave': 'electronic',
    'soul': 'soul',
    'sound team': 'soundtrack',
    'soundtrack': 'soundtrack',
    'south african house': 'electronic',
    'south african pop': 'pop',
    'south carolina hip hop': 'hip hop',
    'southern hip hop': 'hip hop',
    'speed up': 'electronic',
    'speedrun': 'electronic',
    'stomp and holler': 'folk',
    'stomp pop': 'pop',
    'sudanese hip hop': 'hip hop',
    'sudanese pop': 'pop',
    'swazi pop': 'pop',
    'swedish pop': 'pop',
    'swedish soul': 'soul',
    'synthpop': 'electronic',
    'synthwave': 'electronic',
    'talent show': 'pop',
    'tempe indie': 'indie',
    'tennessee hip hop': 'hip hop',
    'thai indie pop': 'pop',
    'thrash metal': 'metal',
    'trance': 'electronic',
    'transpop': 'pop',
    'trap': 'hip hop',
    'trap argentino': 'hip hop',
    'trap chileno': 'hip hop',
    'trap italiana': 'hip hop',
    'trap latino': 'hip hop',
    'trap metal italiana': 'hip hop',
    'trap queen': 'hip hop',
    'trap soul': 'hip hop',
    'trap triste': 'hip hop',
    'traphall': 'hip hop',
    'traprun': 'hip hop',
    'trinibad': 'hip hop',
    'trip hop': 'electronic',
    'tropical house': 'electronic',
    'turkish trap': 'hip hop',
    'turntablism': 'hip hop',
    'uk contemporary r&b': 'r&b',
    'uk dance': 'electronic',
    'uk dancehall': 'reggae',
    'uk drill': 'hip hop',
    'uk hip hop': 'hip hop',
    'uk pop': 'pop',
    'ukrainian hip hop': 'hip hop',
    'underground hip hop': 'hip hop',
    'urban contemporary': 'r&b',
    'urbano chileno': 'hip hop',
    'urbano espanol': 'hip hop',
    'urbano latino': 'hip hop',
    'vapor pop': 'pop',
    'vapor soul': 'soul',
    'vapor trap': 'hip hop',
    'vapor twitch': 'electronic',
    'venezuelan hip hop': 'hip hop',
    'venezuelan rock': 'rock',
    'viral pop italiano': 'pop',
    'vocal house': 'electronic',
    'washington indie': 'indie',
    'wavy hair': 'hip hop',
    'west coast rap': 'hip hop',
    'west virginia hip hop': 'hip hop',
    'west yorkshire indie': 'indie',
    'witch house': 'electronic',
    'woman': 'pop',
    'world': 'world',
    'world worship': 'worship',
    'worship': 'worship',
    'worshipper': 'worship',
    'yacht rock': 'rock',
    'zapstep': 'electronic',
    'zillertal': 'electronic',
    'zim gospel': 'gospel'
}

def map_genre_to_macro_category(genre):
    return macro_category_mapping.get(genre.lower(), 'altro')

genre = "Hip Hop"
macro_category = map_genre_to_macro_category(genre)
# print(f"Il genere '{genre}' appartiene alla macrocategoria '{macro_category}'")
